### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by smcommits** [sinansevgi/programming_articles#2]
Great Project! It reflects great efforts and thoughtful practices. The overall layout is very pleasant and the slider menu for mobile is a nice add-on.
To improve the project further, you can add integration tests. It helps to determine a smooth flow between different independent units of your application. 

Happy Coding!

**Comment by sinansevgi** [comment]
Hello Team,
Thank you for your suggestions. I implemented integration tests as you suggested.

Happy Coding!
